<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <LangVersion>12</LangVersion>
    <AssemblyName>TrackerPlayer.UI</AssemblyName>
    <RootNamespace>TrackerPlayer.UI</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TrackerPlayer.Core\TrackerPlayer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Fonts\protracker-fix.ttf" />
    <Resource Include="Assets\Fonts\ft2font.ttf" />
    <Resource Include="Assets\Fonts\ft2font-notes.ttf" />
  </ItemGroup>
</Project>
